#!/bin/bash

source /etc/cloudrun/client.conf

# TODO: handle errors
set -e

function background () {
    function cleanup () {
        kill "$DPID"
        rm -f "$PID_FILE"
        rm -f "$CONTROL_FIFO"
        echo "Session closed" >> "$LOG_FILE"
        exit
    }

    trap cleanup SIGTERM SIGINT SIGHUP EXIT

    source /etc/cloudrun/client.conf

    echo "$$" > "$PID_FILE"

    DPORT="$(($(id -u) + 30000))"

    echo "Starting daemon on port $DPORT" >> "$LOG_FILE"
    cloudrun-client-daemon serve 0.0.0.0:"$DPORT" >> "$LOG_FILE" 2>&1 &
    export DPID="$!"

    echo "Connecting..." >> "$LOG_FILE"

    cat "$CONTROL_FIFO" | ssh root@"$1" -R 30000:127.0.0.1:"$DPORT" -L "$SSH_PORT":172.30.30.2:22 -x -o ServerAliveInterval=60 cloudrun-worker >> "$LOG_FILE" 2>&1

    exit
}

export -f background

if [ $# -ne 1 ]; then
    echo "Usage: cloudrun-connect <node-address>"
    exit 1
fi

if [ -f "$PID_FILE" ]; then
    if [ -e /proc/"$(< ${PID_FILE})" ]; then
        echo "Close existing session first"
        exit 1
    fi
fi

rm -f "$PID_FILE"
rm -f "$CONTROL_FIFO"
rm -f "$LOG_FILE"

if [ ! -f "$FS_META_FILE" ]; then
    cloudrun-scan
fi

echo "Syncing metadata"

# Upload meta file
rsync -auz  "$FS_META_FILE" root@"$1":/root/filesystem.meta

mkfifo "$CONTROL_FIFO"
echo "Starting session" > "$LOG_FILE"
echo "Starting session"

nohup bash -c "background $1" </dev/null >/dev/null 2>&1 &

function kill_background () {
    if [ -f "$PID_FILE" -a -e /proc/"$(< ${PID_FILE})" ]; then
        echo q > "$CONTROL_FIFO"
        inotifywait -qq -t 2 -e delete_self "$PID_FILE" || kill "$(< ${PID_FILE})"
        exit 0
    fi
    exit 1
}

trap kill_background SIGTERM SIGINT SIGHUP

tail -f "$LOG_FILE" | while read LINE; do
    echo "$LINE"
    if grep "\(ERROR:\|command not found\)" > /dev/null <<< "$LINE"; then
        kill_background
        exit 1
    fi
    if grep "Worker started" > /dev/null <<< "$LINE"; then
        exit 0
    fi
done
